---
title: 'Report Transformative Change Literature Search Chapter 2'
author: Rainer M Krug [Rainer.Krug@Senckenberg.de](mailto:Rainer.Krug@Senckenberg.de)
format:
    html:
        toc: true
        embed-resources: true
        code-fold: true
        code-summary: 'Show the code'
params:
    s_tfc: "('transformative change' OR 'deliberate transformation*' OR 'transformative turn*' OR 'transition*' OR 'social-ecological change*' OR 'deep change' OR 'fundamental alteration' OR 'profound change' OR 'profound transformation' OR 'radical transformation' OR 'transformational change' OR 'complete change' OR 'complete transformation' OR 'drastic change' OR 'in-depth transformation' OR 'progressive change' OR 'radical alteration' OR 'radical change' OR 'revolutionary change' OR 'significant modification' OR 'total transformation' OR 'transition' OR 'pathway' OR 'power' OR 'agency' OR 'scal*' OR 'lever*' OR 'context' OR 'process' OR 'regime' OR 'shift' OR 'views' OR 'value*' OR 'structure*' OR 'institution*' OR 'deliberate' OR 'structural' OR 'fundamental' OR 'system*' OR 'deep' OR 'radical' OR 'profound' OR 'drastic' OR 'widespread' OR 'politic*' OR 'economic*' OR 'structur*' OR 'complete' OR 'progressive' OR 'revolutionary' OR 'substanti*' OR 'significan*') AND ('transformati*' OR 'alteration' OR 'change' OR 'turn' OR 'action' OR 'transition' OR 'shift')"
    s_tfc_5: "('transformative change' OR 'deliberate transformation*' OR 'transformative turn*' OR 'transition*' OR 'social-ecological change*' OR 'deep change' OR 'fundamental alteration' OR 'profound change' OR 'profound transformation' OR 'radical transformation' OR 'transformational change' OR 'complete change' OR 'complete transformation' OR 'drastic change' OR 'in-depth transformation' OR 'progressive change' OR 'radical alteration' OR 'radical change' OR 'revolutionary change' OR 'significant modification' OR 'total transformation' OR 'transformational shift' OR 'radical shift')"
    s_tfc_new: "( 'complete change' OR 'complete transformation' OR 'deep change' OR 'deliberate transformation*' OR 'drastic change' OR 'fundamental alteration' OR 'in-depth transformation' OR 'profound change' OR 'profound transformation' OR 'progressive change' OR 'radical alteration' OR 'radical change' OR 'radical shift' OR 'radical transformation' OR 'revolutionary change' OR 'significant modification' OR 'social-ecological change*' OR 'total transformation' OR 'transform* change' OR 'transform* shift' OR 'transform* turn*' OR 'transition*' )"
    s_nat: "('sustainab*' OR 'environ*' OR 'resilien*' OR 'conserv*' OR 'biodivers*' OR 'ecosystem*' OR 'nature*' OR 'planet*' OR 'Earth' OR 'biosphere')"
    s_nat_5: "('sustainab*' OR 'environ*' OR 'resilien*' OR 'conserv*' OR 'biodivers*' OR 'ecosystem*' OR 'nature*')"
    s_nat_va: "(nature NOT 'nature of' NOT 'by its nature' OR biodiversity OR marine OR terrestrial OR forest* NOT 'random forest' OR woodland* OR grassland* OR savanna* OR shrubland* OR peatland OR ecosystem* OR lake* OR river* OR sea OR ocean* OR meadow* OR heathland* OR mires OR bog* OR tundra OR biosphere OR desert* OR mountain* OR 'natural resource*' OR estuar* OR fjord* OR fauna OR flora OR soil* OR 'coastal waters' OR 'wetland*' OR 'freshwater' OR 'marshland' OR 'marches' OR 'dryland*' OR seascape* OR landscape* OR 'coast*' OR 'arable land*' OR 'agricultural land*' OR 'natural environment*' OR 'environmental resource*' OR 'agroforest*' OR 'agro-forest*' OR 'plantation*' OR 'protected areas' OR chaparral)"
    s_nat_va_new: "(nature NOT 'by its nature' OR biodiversity OR marine OR terrestrial OR forest* NOT 'random forest' OR woodland* OR grassland* OR savanna* OR shrubland* OR peatland OR ecosystem* OR lake* OR river* OR sea OR ocean* OR meadow* OR heathland* OR mires OR bog* OR tundra OR biosphere OR desert* OR mountain* OR 'natural resource*' OR estuary OR fjord* OR fauna OR flora OR soil* OR 'coastal waters' OR 'wetland*' OR 'freshwater' OR 'marshland' OR 'marches' OR 'dryland*' OR seascape* OR landscape* OR 'coast*' OR 'arable land*' OR 'agricultural land*' OR 'natural environment*' OR 'environmental resource*' OR 'agroforest*' OR 'agro-forest*' OR 'plantation*' OR 'protected areas' OR chaparral OR 'socio-ecological')"
    s_vis: "('vision' OR 'future' OR 'visionar*' OR 'scenarios' OR 'imagination' OR 'imager*' OR 'creativity' OR 'desire' OR 'wish*' OR 'visioning' OR 'process' OR 'participatory process*' OR 'deliberate process*' OR 'polic*' OR 'target' OR 'view*' OR 'value' OR 'cosmovision' OR 'cosmocentric' OR 'dream*' OR 'fiction' OR 'hope' OR 'mission' OR 'objective' OR 'story' OR 'worldview*' OR 'aspiration*' OR 'action' OR 'plan*' OR 'strateg*' OR 'intention' OR 'model*' OR 'solution*' OR 'innovation*' OR 'perspective' OR 'platform' OR 'collective action' OR 'cooperation' OR 'consultation' OR 'coalition*' OR 'response' OR 'movement' OR 'effort' OR 'initiative' OR 'activity' OR 'reaction' OR 'performance' OR 'operation' OR 'effect*' OR 'task' OR 'project' OR 'influence' OR 'moment' OR 'discourse' OR 'motivation' OR 'iteration' OR 'roadmap' OR 'agenda' OR 'project' OR 'programm' OR 'government' OR 'technique'  OR 'inspiration' OR 'culture' OR 'universe*' OR 'reality' OR 'fantasy' OR 'perception' OR 'visualization' OR 'approach' OR 'image' OR 'arquetype' OR 'existence' OR 'cosmolog*' OR 'co-production' OR 'knowledge' OR 'dialogue' OR 'transmission' OR 'conceptual*' OR 'ceremon*' OR 'relationships' OR 'respect' OR 'reciprocity' OR 'responsibilities' OR 'solidarity' OR 'harmony' OR 'self-determination' OR 'communit*' OR 'spiritual*' OR 'languague' OR 'territory' OR 'opportunit*' OR 'sight' OR 'foresight' OR 'idea' OR 'appearance')"
    s_case: "('case stud*' OR 'case' OR 'study area*' OR 'example*' OR 'evaluation' OR 'concrete' OR 'empirical', OR 'practical' OR 'initiative*')"
---


# Working Title
Create Network from Search

# Introduction
I will try to reconstruct the citation network from a search.

```{r}
#| label: setup
#| include: false
#|

if (!exists("params")) {
  params <- rmarkdown::yaml_front_matter("~/Documents_Local/git/IPBES_data_tsu/Assessments/Transformative Change/IPBES_TFC_Ch2_Vision/Status.qmd")$params
}

library(openalexR)
library(dplyr)

library(knitr)
library(tictoc)

library(ggraph)
library(tidygraph)

if (!require("IPBES.R")) {
  install.packages("IPBES.R", repos = c("https://ipbes-data.r-universe.dev", "https://cloud.r-project.org"))
  if (!require("IPBES.R")) {
    stop("Package `IPBES.R` is not available and could not be installed!")
  }
}
```

# Search Term Definition
## Overview
```{r}
#| label: create_network
#|

tic()
fn <- file.path(".", "data", "tmp_search.rds")
if (file.exists(fn)) {
  search <- readRDS(fn)
} else {
  source(file.path("R", "oa_query_new.R"))
  search <- oa_query_new(
    search = paste0(
      "(", params$s_tfc_5, ")", " AND ",
      "(", params$s_nat_5, ")"
    ),
    options = list(seed = 13, sample = 10000)
  ) |>
    openalexR::oa_request(
      count_only = FALSE,
      per_page = 200,
      paging = "page"
    )
  saveRDS(search, file = fn)
}
toc()
```

## Creation of Citation Network

```{r}
#| label: creat_citation_network
#|

fn <- file.path(".", "data", "tmp_citation_network.rds")
if (file.exists(fn)) {
  network <- readRDS(fn)
} else {
  network <- list(
    nodes = oa2df(search,
      entity = "works",
      verbose = TRUE
    )
  )

  network$edges <- pbmcapply::pbmclapply(
    search,
    function(work) {
      data.frame(
        from = rep(work$id, length(work$referenced_works)),
        to = unlist(work$referenced_works)
      )
    },
    mc.cores = 8
  ) |>
    dplyr::bind_rows() |>
    filter(to %in% from)
  saveRDS(network, file = fn)
}
```

## Create Graph
```{r}
#| label: create_graph
p_cb <- network |>
  as_tbl_graph() |>
  ggraph(graph = , layout = "stress") +
  geom_edge_link(aes(alpha = after_stat(index)), show.legend = FALSE) +
  geom_node_point(aes(fill = oa_input, size = cited_by_count), shape = 21, color = "white") +
  geom_node_label(aes(filter = oa_input, label = id), nudge_y = 0.2, size = 3) +
  scale_edge_width(range = c(0.1, 1.5), guide = "none") +
  scale_size(range = c(3, 10), guide = "none") +
  scale_fill_manual(values = c("#a3ad62", "#d46780"), na.value = "grey", name = "") +
  theme_graph() +
  theme(
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.background = element_rect(fill = "transparent", colour = NA),
    legend.position = "bottom"
  ) +
  guides(fill = "none") +
  ggtitle("Cited by count")

```